name: Lint and Test PR
on: pull_request

jobs:
  Test-And-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache-dependency-path: server/go.sum

      # - name: lint
      #   run: task lint

      - name: Run tests
        run: go test -v ./...
