name: Lint and Test Main
on:
  push:
    branches:
      - main
jobs:
  Test-And-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache-dependency-path: go.sum

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: lint
        run: task lint

      - name: Run tests
        run: task test:all
